### ISSUE TITLE
Conditional Expectation great_expectations condition_parser

### ISSUE THREAD

**Issue by victorgrcp** [great-expectations/great_expectations#10545]
**Describe the bug**
I'm trying to use a Conditional Expectations for a Databricks table and I'm getting an Exception regarding the condition_parser: "SqlAlchemyExecutionEngine only supports the great_expectations condition_parser"

I'm using a table from a Databricks SQL Warehouse as a data asset.

**Code**
```
cond_expectation = gxe.ExpectColumnValuesToBeInSet(
    column="tpep_dropoff_datetime",
    value_set=[datetime(2016, 1, 1, 0, 12), datetime(2016, 1, 1, 0, 13)],
    condition_parser="great_expectations",
    row_condition='col(pickup_zip)==10001',
)
batch.validate(cond_expectation)
```

**Full stack trace of any error**
"exception_info": {
    "('table.row_count', '6819aaaf24faa4118ff0b899d5019b79', ())": {
      "exception_traceback": "Traceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/execution_engine/execution_engine.py\", line 546, in _process_direct_and_bundled_metric_computation_configurations\n    self.resolve_metric_bundle(metric_fn_bundle=metric_fn_bundle_configurations)\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py\", line 1010, in resolve_metric_bundle\n    selectable: sqlalchemy.Selectable = self.get_domain_records(domain_kwargs=domain_kwargs)\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py\", line 660, in get_domain_records\n    raise GreatExpectationsError(  # noqa: TRY003\ngreat_expectations.exceptions.exceptions.GreatExpectationsError: SqlAlchemyExecutionEngine only supports the great_expectations condition_parser.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/validator/validation_graph.py\", line 276, in _resolve\n    self._execution_engine.resolve_metrics(\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/execution_engine/execution_engine.py\", line 279, in resolve_metrics\n    return self._process_direct_and_bundled_metric_computation_configurations(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/great_expectations/execution_engine/execution_engine.py\", line 550, in _process_direct_and_bundled_metric_computation_configurations\n    raise gx_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: SqlAlchemyExecutionEngine only supports the great_expectations condition_parser.\n",
      "exception_message": "SqlAlchemyExecutionEngine only supports the great_expectations condition_parser.",
      "raised_exception": true

**Expected behavior**
That the Expectation is validated agains my batch.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 1.1.3
 - Data Source: Databricks SQL Warehouse
 - Cloud environment: Azure Databricks

**Comment by adeola-ak** [comment]
hey there, are you using spark to read from the databricks table? for example: 
`dataframe = spark.sql("SELECT * FROM demo.default.nyc_taxi_data LIMIT 10")`

if so, can you try changing the parser to "spark" and then updating the row condition to use standard SQL syntax:

```
from datetime import datetime
import great_expectations as gx

cond_expectation = gx.expectations.ExpectColumnValuesToBeInSet(
    column="tpep_dropoff_datetime",
    value_set=[
        datetime(2016, 1, 1, 0, 12),
        datetime(2016, 1, 1, 0, 13),
    ],
    condition_parser="spark",
    row_condition='`pickup_zip` = 10001'  
)

batch.validate(cond_expectation)
```

if this isn't helpful please share more of your script, specifically how you are reading the data from the databricks table

**Comment by victorgrcp** [comment]
Hi @adeola-ak thanks for the fast response, what you suggested haven't solve the problem. I'm using the function `add_databricks_sql` to access the data source and assets:
```
databricks_data_source = "sql_warehouse"

try:
    data_source = context.data_sources.add_databricks_sql(name=databricks_data_source, connection_string=connection_string)
except Exception as e:
    data_source = context.get_datasource(name=databricks_data_source)
    print("Error: ", e, "\n")
```
then use,
`table_data_asset = data_source.add_table_asset(
        table_name=database_table_name, name=asset_name
)`
and a whole batch definition,
`add_batch_definition_whole_table`

**Comment by adeola-ak** [comment]
Hi @victorgrcp. thank you for providing more details about your environment. I was able to reproduce the issue locally when using SQLAlchemy to connect to a table in Databricks. interestingly, I didn't encounter any problems when using Spark. I will escalate this to the team and circle back with you when i have more info, thanks for bringing this to our attention

**Comment by adeola-ak** [comment]
hey @victorgrcp can you upgrade to 1.2? this was addressed in 1.2

**Comment by victorgrcp** [comment]
Hi! I still have this problem when trying to use **row_condition**. No matter how I write the condition I always get an error.

I'm using GX 1.3.3 and pyspark 3.5.0.

The data asset is a simple pyspark DF:
`df = spark.createDataFrame([("accepted", "-1", 1), ("rejected", "-1", 2), ("new", "-1", 3), ("dismissed", "-1", 4), ("canceled", "1", 5)], ["status_code", "offer_id", "integration_id"])`

Parameters:
```
import os
os.environ["GX_ANALYTICS_ENABLED"] = "false"
from json import loads
import great_expectations as ge
import importlib

catalog = "dbw_gt_data_uat_lake_catalog"
schema  = "js_gold"
table_name = "gld_fact_jobseeker_offer"
column = "status_code"
table_key_list = ["integration_id"] # List of PK columns
expectation_name = "ExpectColumnValuesToBeInSet"
args = {"column": "status_code", "value_set": ["accepted", "canceled", "new", "rejected", "dismissed"]}
condition_parser = "spark"
row_condition = "`integration_id` = 1"
args.update({"row_condition": row_condition}, **{"condition_parser": condition_parser})
```

The functions I'm using to create the context and test the expectation:
```
def my_import(name: str, arguments: dict) -> object:
    """Import a specific Expectation Class from GX Expectation module"""
    module = importlib.import_module("great_expectations.expectations")
    return getattr(module, name)(**arguments)
```
```
def test_expectation(df = None):
    context = ge.get_context()
    data_name = f"{catalog}.{schema}.{table_name}"
    data_source = context.data_sources.add_spark(name=data_name)
    data_asset = data_source.add_dataframe_asset(name=table_name)
    
    if not df:
        batch_parameters = {
            "dataframe": 
                spark.read.table(f"{catalog}.{schema}.{table_name}").limit(100)
            }
    else:
        batch_parameters = {"dataframe": df}
    
    expectation_suite = context.suites.add(ge.core.expectation_suite.ExpectationSuite(name=f"s-{data_name}"))
    
    # Get the expectation class
    gx_expectation = my_import(expectation_name, args)
    expectation_suite.add_expectation(gx_expectation)
        
    batch_definition = data_asset.add_batch_definition_whole_dataframe(
        name="batch_definition"
    )
    validation_definition = context.validation_definitions.add(
            ge.core.validation_definition.ValidationDefinition(
                name=f"vd-{data_name}",
                data=batch_definition,
                suite=expectation_suite,
            )
    )
    checkpoint = context.checkpoints.add(
        ge.Checkpoint(
            name=f"cp-{data_name}",
            validation_definitions=[validation_definition],
            result_format={
                "result_format": "COMPLETE",
                "unexpected_index_column_names": table_key_list,
                "partial_unexpected_count": 0,
                "exclude_unexpected_values": False,
                "include_unexpected_rows": True,
                "return_unexpected_index_query": False,
            },
        )
    )
    return checkpoint.run(batch_parameters=batch_parameters)

test_expectation(df)
```

The exception message is:
```
"success": false,
"expectation_config": {
"type": "expect_column_values_to_be_in_set",
"kwargs": {
"column": "status_code",
"row_condition": "`integration_id` = 1",
"condition_parser": "spark",
"value_set": [
            "accepted",
            "canceled",
            "new",
            "rejected",
            "dismissed"
          ],
"batch_id": "dbw_gt_data_uat_lake_catalog.js_gold.gld_fact_jobseeker_offer-gld_fact_jobseeker_offer"},
"meta": {},
"id": "7b9f83e5-e51f-4a2b-aeb0-74f2411a4a5e"},
"result": {},
"meta": {},
"exception_info": {
        "('column_values.in_set.unexpected_rows', '65db743c0377a9eef50edd831b9cf172', '0e857f57c80f9f821bc18fba200b2f0e')": {
          "exception_traceback": "Traceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-3a40391b-2b84-49b1-93c6-5fbd37efd62e/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py\", line 532, in _process_direct_and_bundled_metric_computation_configurations
metric_computation_configuration.metric_fn(  # type: ignore[misc] # F not callable\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-3a40391b-2b84-49b1-93c6-5fbd37efd62e/lib/python3.10/site-packages/great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py\", line 655, in _spark_map_condition_rows\n    return filtered.limit(MAX_RESULT_RECORDS).collect()
File \"/databricks/spark/python/pyspark/sql/connect/dataframe.py\", line 1833, in collect\n    table, schema = self._to_table()\n  
File \"/databricks/spark/python/pyspark/sql/connect/dataframe.py\", line 1868, in _to_table\n    table, schema = self._session.client.to_table(query, self._plan.observations)\n  
File \"/databricks/spark/python/pyspark/sql/connect/client/core.py\", line 990, in to_table\n    table, schema, _, _, _ = self._execute_and_fetch(req, observations)\n  
File \"/databricks/spark/python/pyspark/sql/connect/client/core.py\", line 1627, in _execute_and_fetch\n    for response in self._execute_and_fetch_as_iterator(\n  
File \"/databricks/spark/python/pyspark/sql/connect/client/core.py\", line 1604, in _execute_and_fetch_as_iterator\n    self._handle_error(error)\n  
File \"/databricks/spark/python/pyspark/sql/connect/client/core.py\", line 1913, in _handle_error\n    self._handle_rpc_error(error)\n  
File \"/databricks/spark/python/pyspark/sql/connect/client/core.py\", line 1988, in _handle_rpc_error\n    raise convert_exception(\npyspark.errors.exceptions.connect.AnalysisException: [CANNOT_RESOLVE_DATAFRAME_COLUMN] Cannot resolve dataframe column \"status_code\". It's probably because of illegal references like `df1.select(df2.col(\"a\"))`.
```

**Comment by victorgrcp** [comment]
@adeola-ak there is anything that I'm doing wrong?
I already tried different syntaxes.

**Comment by adeola-ak** [comment]
hi @victorgrcp i will check in on this today

**Comment by victorgrcp** [comment]
Hi @adeola-ak any news about this?

**Comment by adeola-ak** [comment]
hi, this doesnt look like the same issue or error as reported prior.  what happens with this same set up if you remove the `condition_parser="spark"` all together? Additionally for Spark, our docs recommend to specify your columns using the col() function. Ex: `row_condition = 'col("PClass")=="1st"'`

**Comment by victorgrcp** [comment]
Hi! I added this problem here because is related with the **row_condition** feature and didn't want to open a new issue.

- If I remove `condition_parser="spark"`, I get: `"exception_message": "unrecognized condition_parser None for Spark execution engine"`
- Keeping **spark** as the parser and updating row condition to: `row_condition = 'col("integration_id")==1'`. I get: 

> "exception_message": "[UNRESOLVED_ROUTINE] Cannot resolve function `col` on search path [`system`.`builtin`, `system`.`session`, `dbw_gt_data_uat_lake_catalog`.`default`]. SQLSTATE: 42883; line 1 pos 0\n\nJVM stack..."

**Comment by adeola-ak** [comment]
hi @victorgrcp im really sorry that you are still having this problem. It's been tricky because we havent quite been able to replicate it. Can you please share more details about your cluster and is it multi or single

**Comment by adeola-ak** [comment]
better yet, Since we've discussed two different examples, this approach might be more effective for resolving the issue permanently: Please summarize exactly what you'd like to achieve with GX, including the data source, environment, and any other relevant details. I'll then ensure I can replicate it without any issues

**Comment by adeola-ak** [comment]
Oh I see you have created a new issue for the most recent example, thanks. We will pick up from there
