### ISSUE TITLE
data docs rendering bug for UnexpectedRowsExpectation

### ISSUE THREAD

**Issue by VolkovGeoPhy** [great-expectations/great_expectations#10547]
**Describe the bug**
https://docs.greatexpectations.io/docs/core/customize_expectations/use_sql_to_define_a_custom_expectation done as it described here.
In any case it doesn't render it in correct way despite I can see correct results in json file.

**To Reproduce**
Create any custom expectation as it described [here](https://docs.greatexpectations.io/docs/core/customize_expectations/use_sql_to_define_a_custom_expectation). build docs. 

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: Docker
 - Great Expectations Version: 1.1.3
 - Data Source: Redshift
 - Cloud environment: no

**Additional context**
![Screenshot 2024-09-30 at 17 44 07](https://github.com/user-attachments/assets/906060b3-d93e-4548-943a-e0bb84e65826)

**Comment by adeola-ak** [comment]
are you executing locally? can you share your script

**Comment by VolkovGeoPhy** [comment]
I've tried it in two ways. Locally and via airflow DAG + s3 storages. 

```
    class ExpectNoGeometriesIntersect(gx.expectations.UnexpectedRowsExpectation):
        unexpected_rows_query: str = batch_query
        description: str = "No geometries should intersect with each other."

    logger.info(f"query={batch_query}")

    register_expectation(ExpectNoGeometriesIntersect)
    expectation = ExpectNoGeometriesIntersect()

    regular_suite.add_expectation(expectation)
```

**Comment by VolkovGeoPhy** [comment]
The issue exits in 1.2.0 as well @adeola-ak. Let me know if you need some additional info.

**Comment by adeola-ak** [comment]
hi there @VolkovGeoPhy thanks for reporting this. I was able to reproduce. I will escalate this and follow up with you shortly

**Comment by adeola-ak** [comment]
Hi there,

This issue has been added to our backlog, and our team will work on it, though we don’t have a timeline yet. If it’s something you’d like to see resolved sooner, you’re more than welcome to [submit a contribution](https://github.com/great-expectations/great_expectations/blob/develop/CONTRIBUTING_CODE.md). Otherwise, please feel free to continue to check this issue for updates. Thank you!

**Comment by iamamutt** [comment]
I found that if I didn't set the `description` field in the expectation config then the content renders correctly. This seems to be the case not just for `UnexpectedRowsExpectation` but other types of expectation classes as well.

**Comment by VolkovGeoPhy** [comment]
eventually it was fixed in 1.3.0

**Comment by higorseixas** [comment]
I’ve updated to Great Expectations version 1.3 but the issue still persists — the same error continues to occur even after upgrading.
