### ISSUE TITLE
Slack notification formatting issues - 0.18.14

### ISSUE THREAD

**Issue by data-han** [great-expectations/great_expectations#9986]
**Is your feature request related to a problem? Please describe.**
I'm just checking in with regards to the new update 0.18.14 on the new slack design. Awesome to have a new look but i would want to check if we could make it better since this is largely used across by everyone

**Describe the solution you'd like**
https://github.com/great-expectations/great_expectations/pull/9952
![image](https://github.com/great-expectations/great_expectations/assets/51312880/55f08cd1-c1ec-4e8c-a3cb-f1ba158ea735)

I wrote in the feature PR regarding this but not sure if it is 'closed' and won't be looked after. Anyway, my team has been using this slack notification for a long time, it is serving our purpose quite well (except that it had this extra filepath issue, im not sure why is that??) . With the new update, it is not as clear as it was before to show the asset name etc

**Describe alternatives you've considered**

**Additional context**
Add any other context, screenshots, or code samples about the feature request here.

**Comment by Kilo59** [comment]
@data-han @jshaikGX 

I believe this was fixed in `0.18.15`
https://github.com/great-expectations/great_expectations/releases/tag/0.18.15 
- https://github.com/great-expectations/great_expectations/pull/9964

**Comment by jshaikGX** [comment]
This was fixed in `0.18.15` 
and yes the design is been updated to be simple now! Please try `0.18.15` and let us know if this is still a problem

**Comment by data-han** [comment]
@Kilo59 @jshaikGX

hello, thanks for looking into this. Much appreciate for your effort! I've tried 0.18.15 but i still see the same. May I know which issue is fixed? I'm still seeing the same except for UTC being added..

- i still see a unexpected file path
- Asset and Suite is not 'bolded'

<img width="584" alt="image" src="https://github.com/great-expectations/great_expectations/assets/51312880/3294c349-3cae-46e2-8822-a7ef2a33e8eb">

**Comment by jshaikGX** [comment]
Will have the team look into this!

**Comment by data-han** [comment]
Adding the same issue raised a year ago. Not sure if anyone can help to visit this topic
https://github.com/great-expectations/great_expectations/issues/7016

**Comment by NathanFarmer** [comment]
@data-han We removed the broken/duplicated link text, but we aren't able to have it show up as a hyperlink for local Data Docs, because Slack does not allow linking to local files due to security concerns. This fix will be available in version 0.18.20.
